Repository julia-vscode/LanguageServer.jl, pull requests merged in 2020-07, with the labels that each got.

#784 fix use of StaticLint.iterate_over_ss_methods
  src/requests/features.jl
Labels: bug

#785 remove two outdated and unused files
  test/debug.jl
  test/test_bruteforce.jl
Labels: bug

#787 fix displaying of docs on hover
  src/requests/hover.jl
Labels: bug

#744 julia/getDocAt handler
  Project.toml
  src/LanguageServer.jl
  src/languageserverinstance.jl
  src/protocol/messagedefs.jl
  src/requests/features.jl
  src/requests/misc.jl
  src/utilities.jl
Labels: enhancement

#788 move julia specific LS extensions to seperate dir
  src/LanguageServer.jl
  src/extensions/extensions.jl
  src/extensions/messagedefs.jl
  src/protocol/document.jl
  src/protocol/messagedefs.jl
Labels: enhancement

#789 show document for `const` variables, follow up #744
  src/requests/features.jl
  src/requests/hover.jl
  src/utilities.jl
Labels: bug

#790 disable lints for docs dir
  src/requests/textdocument.jl
  src/utilities.jl
  test/test_paths.jl
Labels: enhancement

#791 Use a command URI for getDocAt
  src/requests/features.jl
  src/utilities.jl
Labels: enhancement

#792 make disabled directories configurable
  src/languageserverinstance.jl
  src/requests/textdocument.jl
  src/requests/workspace.jl
Labels: enhancement

#793 Use MD for julia_getDocAt_request, remove all VS Code specifics
  src/requests/features.jl
  src/utilities.jl
Labels: enhancement

#794 Fix a race condition for progress tokens
  src/languageserverinstance.jl
Labels: bug

#798 Fix tests
  src/languageserverinstance.jl
  test/runtests.jl
  test/test_actions.jl
  test/test_edit.jl
  test/test_intellisense.jl
Labels: Showstopper, bug

#800 Escape from get_func_hover loop
  src/requests/features.jl
  src/requests/hover.jl
Labels: bug

#805 Use proper string for expansion to default env
  src/runserver.jl
Labels: bug

#807 Fix an offset bug
  src/requests/features.jl
Labels: bug
