Repository julia-vscode/LanguageServer.jl, pull requests merged in 2020-06, with the labels that each got.

#737 check retrieve_toplevel_scope has returned a scope
  src/requests/actions.jl
Labels: bug

#738 Refactor -> anonymous function
  src/languageserverinstance.jl
Labels: enhancement

#743 method jump in hover
  src/requests/hover.jl
Labels: enhancement

#755 alter getCurrentBlockRange request
  src/requests/misc.jl
Labels: bug

#756 fix FormatOptions inconsistency
  src/requests/workspace.jl
Labels: bug

#760 add special JSON handler for DidChangeConfigurationParams
  src/protocol/configuration.jl
Labels: bug

#758 Use JSONRPC version of @dict_readable
  Project.toml
  src/LanguageServer.jl
  src/protocol/basic.jl
  src/protocol/protocol.jl
Labels: enhancement

#761 simplify kw completion snippet code
  src/requests/completions.jl
Labels: bug, enhancement

#765 nothing -> missing in WorkspaceEdit
  src/requests/actions.jl
  src/requests/features.jl
Labels: bug

#775 Fix WorkspaceEdit (again)
  src/requests/actions.jl
Labels: bug

#773 more careful getModuleAt
  src/requests/features.jl
Labels: bug

#780 return completions as plaintext by default
  src/protocol/completion.jl
  src/requests/completions.jl
Labels: bug

#779 replace loops with recursion
  src/exception_types.jl
  src/requests/features.jl
  src/requests/hover.jl
  src/requests/textdocument.jl
  src/utilities.jl
Labels: bug

#778 check docversion in module/blockrange requests
  src/protocol/document.jl
  src/protocol/messagedefs.jl
  src/requests/features.jl
  src/requests/misc.jl
Labels: bug

#783 Add SymbolServer 5 to compat
  Project.toml
Labels: enhancement
