Repository julia-vscode/LanguageServer.jl, pull requests merged in 2020-05, with the labels that each got.

#654 Add option for symbol server store path
  Project.toml
  src/languageserverinstance.jl
Labels: enhancement

#655 Add a request for help to tricky bug
  src/requests/textdocument.jl
Labels: bug

#661 fix didClose file deleting logic
  src/requests/textdocument.jl
Labels: bug

#665 Don't send missing fields
  src/protocol/basic.jl
  src/protocol/protocol.jl
Labels: bug

#667 Update docstring
  src/languageserverinstance.jl
Labels: enhancement

#670 fix single line function expansion
  src/requests/actions.jl
Labels: bug

#576 Make deletedocument! more robust
  src/languageserverinstance.jl
Labels: bug

#672 Make a piece of code easier to understand for DA
  src/languageserverinstance.jl
Labels: enhancement

#676 fix goto def for imported DataTypes
  src/requests/features.jl
Labels: bug

#679 update signature for SL.collect_hints
  Project.toml
  src/requests/textdocument.jl
Labels: dep bump required

#678 support for func arg use check in SL
  src/protocol/basic.jl
  src/requests/textdocument.jl
  src/requests/workspace.jl
Labels: dep bump required

#680 remove reference to StaticLint.setpath
  src/staticlint.jl
Labels: bug

#683 update config & lint checks, remove unneeded fields
  Project.toml
  src/document.jl
  src/languageserverinstance.jl
  src/requests/textdocument.jl
  src/requests/workspace.jl
  src/utilities.jl
Labels: dep bump required

#684 Hide a bug on Julia 1.2.0
  src/requests/features.jl
Labels: bug

#691 Simplify configuration code
  src/languageserverinstance.jl
  src/requests/textdocument.jl
  src/requests/workspace.jl
  src/staticlint.jl
Labels: enhancement

#690 Add auto fix for some missing refs
  src/requests/actions.jl
  src/requests/init.jl
  test/runtests.jl
  test/test_actions.jl
Labels: enhancement

#693 Check client accepts workspace/config requests
  src/languageserverinstance.jl
  src/requests/init.jl
  src/requests/workspace.jl
Labels: bug

#698 fix typos
  src/requests/workspace.jl
Labels: bug

#697 add "julia/getCurrentModule" handler
  src/requests/features.jl
Labels: enhancement

#699 Fix test_path tests
  test/runtests.jl
  test/test_edit.jl
  test/test_paths.jl
Labels: discussion, non-vscode

#704 Add check for relative paths
  src/exception_types.jl
  src/utilities.jl
Labels: bug

#702 Add escaping when comparing/hashing URI2
  src/uri2.jl
  src/utilities.jl
  test/test_paths.jl
Labels: enhancement

#705 Make sure we can't load empty paths
  src/staticlint.jl
Labels: bug

#710 fix collec_extended_methods bug
  src/languageserverinstance.jl
Labels: bug

#696 interperet `nothin` -> false in client config response handling
  src/languageserverinstance.jl
  src/requests/init.jl
  src/requests/workspace.jl
Labels: bug

#646 Make path in Document optional
  src/document.jl
  src/requests/completions.jl
  src/requests/features.jl
  src/requests/textdocument.jl
  src/staticlint.jl
  src/utilities.jl
Labels: bug

#701 Rewrite msg dispatch
  Project.toml
  src/LanguageServer.jl
  src/jsonrpc.jl
  src/jsonrpcendpoint.jl
  src/languageserverinstance.jl
  src/protocol/basic.jl
  src/protocol/completion.jl
  src/protocol/document.jl
  src/protocol/features.jl
  src/protocol/formatting.jl
  src/protocol/goto.jl
  src/protocol/highlight.jl
  src/protocol/hover.jl
  src/protocol/initialize.jl
  src/protocol/messagedefs.jl
  src/protocol/protocol.jl
  src/protocol/signature.jl
  src/protocol/symbols.jl
  src/requests/actions.jl
  src/requests/completions.jl
  src/requests/features.jl
  src/requests/hover.jl
  src/requests/init.jl
  src/requests/misc.jl
  src/requests/textdocument.jl
  src/requests/workspace.jl
  src/staticlint.jl
  test/test_actions.jl
  test/test_communication.jl
  test/test_edit.jl
  test/test_hover.jl
Labels: enhancement

#714 use get_expr rather than get_expr1
  src/requests/features.jl
Labels: bug

#715 change workspace/config check
  src/requests/workspace.jl
Labels: bug

#717 Fix config handling
  src/requests/workspace.jl
Labels: bug

#718 some minor doc handling changes
  src/languageserverinstance.jl
  src/requests/textdocument.jl
Labels: bug

#724 Add isnothing for Julia < 1.1
  src/requests/workspace.jl
Labels: bug

#720 don't suggest gensymed names for completions
  src/requests/completions.jl
Labels: bug

#721 enable path completions on homedir
  src/requests/completions.jl
Labels: enhancement

#728 change LSHoverError reporting
  src/requests/hover.jl
Labels: bug

#726 fix off by one in sig helper
  src/requests/features.jl
  test/runtests.jl
  test/test_intellisense.jl
Labels: bug

#727 pre-empt incoming staticlint change
  src/utilities.jl
Labels: enhancement

#733 Remove while loop, fix symbol lookup
  src/requests/hover.jl
  src/utilities.jl
Labels: bug
