Repository julia-vscode/LanguageServer.jl, pull requests merged in 2020-08, with the labels that each got.

#813 disable incremental document updates
  src/requests/init.jl
Labels: bug

#803 enhance completions:
  src/requests/completions.jl
  src/requests/init.jl
Labels: enhancement

#811 fix latex completions with multiple cursors
  src/requests/completions.jl
Labels: bug

#816 add ^ to completion triggers
  src/requests/init.jl
Labels: bug

#821 Fix for ProgressToken typing
  src/protocol/basic.jl
  src/protocol/features.jl
  src/protocol/goto.jl
  src/protocol/highlight.jl
  src/protocol/hover.jl
  src/protocol/initialize.jl
  src/protocol/signature.jl
  src/protocol/symbols.jl
Labels: bug, non-vscode

#820 Update completions.jl
  src/requests/completions.jl
Labels: bug

#825 typo
  src/requests/hover.jl
Labels: bug
