Repository julia-vscode/LanguageServer.jl, pull requests merged in 2021-01, with the labels that each got.

#859 fix for jmd parsing
  src/requests/textdocument.jl
Labels: bug

#810 backlog: add getDocFromWord handler
  src/extensions/messagedefs.jl
  src/languageserverinstance.jl
  src/requests/features.jl
  src/utilities.jl
Labels: enhancement

#863 check string literal has a val
  src/requests/features.jl
Labels: bug

#862 Incremental update for cst/semantic
  Project.toml
  src/document.jl
  src/languageserverinstance.jl
  src/requests/init.jl
  src/requests/textdocument.jl
Labels: enhancement

#866 Update to new client lib version
  src/requests/workspace.jl
Labels: Showstopper, bug

#867 Fix another bug caused by new LS client
  src/requests/workspace.jl
Labels: Showstopper, bug

#869 Replace single arg JSON RPC types
  src/extensions/messagedefs.jl
  src/protocol/messagedefs.jl
  src/requests/features.jl
  src/requests/misc.jl
Labels: Showstopper, bug

#868 add msg handlers for setTrace
  src/languageserverinstance.jl
  src/protocol/basic.jl
  src/protocol/messagedefs.jl
  src/requests/misc.jl
Labels: bug

#873 Add more diagnostics
  src/document.jl
Labels: bug

#874 don't try incremental update for jmd, check CST matches string length
  src/requests/textdocument.jl
Labels: bug
