Repository julia-vscode/LanguageServer.jl, pull requests merged in 2021-03, with the labels that each got.

#904 improve shutdown request handling
  src/languageserverinstance.jl
  src/requests/init.jl
Labels: bug

#905 better getModuleAt
  src/document.jl
  src/requests/features.jl
  src/utilities.jl
Labels: bug

#897 Safe load
  src/requests/features.jl
  src/staticlint.jl
Labels: bug

#907 better shutdown handling
  src/languageserverinstance.jl
Labels: enhancement

#914 fix find_references
  src/requests/features.jl
Labels: bug

#893 selection ranges
  src/languageserverinstance.jl
  src/protocol/messagedefs.jl
  src/requests/features.jl
  src/requests/init.jl
Labels: enhancement, needs changelog

#906 allow fuzzy completions
  src/requests/completions.jl
Labels: enhancement
