Repository julia-vscode/LanguageServer.jl, pull requests merged in 2021-07, with the labels that each got.

#965 Enable cloud download
  src/languageserverinstance.jl
Labels: enhancement

#963 add rd/prepareRename
  src/languageserverinstance.jl
  src/protocol/messagedefs.jl
  src/requests/features.jl
  src/requests/init.jl
  test/test_communication.jl
Labels: bug

#969 Fix env_project_file usage
  src/multienv.jl
Labels: Showstopper, bug

#967 remove hover message for closing function call parenthesis
  src/requests/hover.jl
  test/requests/hover.jl
Labels: enhancement
